# Generated by Django 3.2.8 on 2021-10-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Название клиента')),
                ('lpr', models.CharField(max_length=150, verbose_name='ФИО ЛПР-а')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('tel_number', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Е-мэил')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('commentary', models.TextField(verbose_name='Коментарии')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('call', 'Звонок'), ('deal', 'Сделка'), ('meeting', 'Встреча')], max_length=50)),
                ('commentary', models.TextField(verbose_name='Коментарии')),
                ('deadline', models.DateTimeField(verbose_name='Сроки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField(verbose_name='Сделка')),
                ('publish', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField(verbose_name='Коментарии')),
                ('publish', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.client')),
            ],
        ),
    ]
